// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PackageSecurity
{
    static class Vsix
    {
        public const string Id = "1fd37423-142f-4267-8221-93163d573b90";
        public const string Name = "Package Security Alerts";
        public const string Description = @"Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.";
        public const string Language = "en-US";
        public const string Version = "0.4";
        public const string Author = "Mads Kristensen";
        public const string Tags = "security, npm, bower, package";
    }
}
